### ISSUE TITLE
subs support

### ISSUE THREAD

**Issue by elgarbe** [leech001/SIM800MQTT#1]
Hi, are you planning to add support for topic subscribe?

thank

**Comment by leech001** [comment]
I didn't think much about it. But if necessary, I can try to implement it.

**Comment by elgarbe** [comment]
It would be really useful.

Can you sugest me some free mqtt broker to test your code? I'm trying with test.mosquitto.org but it seems to close my connection when I've try to send pub command.

**Comment by leech001** [comment]
> It would be really useful.
> 
> Can you sugest me some free mqtt broker to test your code? I'm trying with test.mosquitto.org but it seems to close my connection when I've try to send pub command.

Hi! Try this service [https://www.cloudmqtt.com/](https://www.cloudmqtt.com/)

**Comment by Vitalik0711** [comment]
Hello! Can you please tell me, do you plan to support the possibility of subscribing to topics?

**Comment by leech001** [comment]
> Hello! Can you please tell me, do you plan to support the possibility of subscribing to topics?

Hi. I will be happy to have your Pull requests.

**Comment by Gleb252** [comment]
Hi, could you please add support for subscription and a callback function in your library. Or at least tell me the materials for studying on this topic.

**Comment by leech001** [comment]
Hi. Added subscription implementation for MQTT to the library. 
**Please test and give feedback!**
For operational questions my account in Telegram _@leech001_.

[https://github.com/leech001/SIM800MQTT/tree/issue_1](https://github.com/leech001/SIM800MQTT/tree/issue_1)

**Comment by Gleb252** [comment]
Да, спасибо, код выглядит рабочим, я почти всё это уже написал, даже переменные также почти назвал. Мне оставалось написать обработчик полученных сообщений. Протестирую - обязательно отпишусь.

**Comment by leech001** [comment]
> Да, спасибо, код выглядит рабочим, я почти всё это уже написал, даже переменные также почти назвал. Мне оставалось написать обработчик полученных сообщений. Протестирую - обязательно отпишусь.

Спасибо. Если что я говно программист и обычно пишу тот еще говнокод. Если будут предложения как его улучшить всегда рад PR.

**Comment by leech001** [comment]
> Hi, could you please add support for subscription and a callback function in your library. Or at least tell me the materials for studying on this topic.

Calllback function will not be able to use, because its call will be made from a UART interrupt on the readiness of the buffer with the received data, and if there is a calllback it will be blocking for this interrupt, which will stop listening to UART. In the new version of the library for this is used flag simply corresponding (SIM800.mqttReceive.newEvent), that came new data.

**Comment by leech001** [comment]
[https://github.com/leech001/SIM800MQTT/releases/tag/sub](https://github.com/leech001/SIM800MQTT/releases/tag/sub)
