### ISSUE TITLE
SUBSCRIBE command sends garbage in reserved bits of maximum QoS field

### ISSUE THREAD

**Issue by grzegorz-kraszewski** [leech001/SIM800MQTT#11]
`MQTTSerialize_subscribe()` takes an **array** of subscription topics strings and an **array** of maximum QoS for these topics. `MQTT_Sub()` always subscribes to one topic. Then it should specify an address of a pointer to topic string (which it does) and an address of a variable containing 0 as maximum QoS. It passes straight 0 instead, which makes `MQTTSerialize_subscribe()` to read QoS level from memory address 0 (MQTTSubscribeClient.c/79). As the whole byte is put into MQTT packet, 6 high, reserved bits of the field may contain random values. Protocol strict brokers like Mosquitto disconnect after receiving such SUBSCRIBE.

**Comment by leech001** [comment]
Please send a pull requests with a correction.
