### ISSUE TITLE
stm32

### ISSUE THREAD

**Issue by Rajrou** [leech001/SIM800MQTT#15]
i want to publish a message in the topic "test" how can i add the instruction

**Comment by leech001** [comment]
I'm sorry I don't understand your question. You can reword it.

**Comment by Rajrou** [comment]
your code doesn't publish a message in the broker i want to publish a message from gsm to the hivemqtt broker like in this video https://youtu.be/OEb5GeWo5hA

**Comment by leech001** [comment]
So the video uses a different library. Apply it  [https://github.com/nimaltd/gsm_v5](https://github.com/nimaltd/gsm_v5)
