### ISSUE TITLE
Sim800_RxCallBack doesn't detect CLOSED or ERROR

### ISSUE THREAD

**Issue by aleite93** [leech001/SIM800MQTT#5]
This issue is caused by the presence of '\0' value in rx_buffer element that occurs before the string CLOSED or ERROR, [strstr](https://www.cplusplus.com/reference/cstring/strstr/) will stop at the occurrence of a terminating null-characters ('\0').

To check this, just decrease the keepAliveInterval and increase the delay in the while(1) loop (i suggest 60 seconds for the delay and 10 seconds for the keepAliveInterval)

To solve this, replace the [line 77 in MQTTSim800.c](https://github.com/leech001/SIM800MQTT/blob/master/src/MQTTSim800.c#L77) with:
`    if ( ( rx_index > 9 && strstr( (char *) &(rx_buffer[rx_index-10]), "\r\nCLOSED\r\n" ) ) || ( rx_index > 8 && strstr( (char *) &(rx_buffer[rx_index-9]), "\r\nERROR\r\n"  ) ) )`

**Comment by leech001** [comment]
Thank you very much for your question. I have reviewed it and am not prepared to agree with your conclusions and suggestions.
Maybe it would be more logical to check for presence of "\0" control character in rx_buffer and just understand it as end of line by analogy with "\r\n"?

Maybe this code will be more efficient? I change [67 line on MQTTSim800.c](https://github.com/leech001/SIM800MQTT/blob/master/src/MQTTSim800.c#L67)
```
 if (SIM800.mqttServer.connect == 0) {
        if (strstr((char *) rx_buffer, "\r\n") != NULL && rx_index == 2) {
            rx_index = 0;
        } else if ((strstr((char *) rx_buffer, "\r\n") != NULL) || (strstr((char *) rx_buffer, "\0") != NULL) {
            memcpy(mqtt_buffer, rx_buffer, sizeof(rx_buffer));
            clearRxBuffer();
            if (strstr(mqtt_buffer, "DY CONNECT\r\n")) {
                SIM800.mqttServer.connect = 0;
            } else if (strstr(mqtt_buffer, "CONNECT\r\n")) {
                SIM800.mqttServer.connect = 1;
            }
        }
    }
```

**Comment by aleite93** [comment]
Hi, that won't work when SIM800.mqttServer.connect is set to 1 and you receive a CLOSED due to a timeout.
