### ISSUE TITLE
SIM800 does not works after receives data from the server.

### ISSUE THREAD

**Issue by killercuts** [leech001/SIM800MQTT#6]
Hello
I was testing your library and can't find the problem after the sim800L receives data from the server (SIM800.mqttReceive.newEvent == 1)
The problem is in my case: after receiving the payload, the system stops working. No published messages, no subscription messages are received .
I debug the code and it is working but the sim800 appears be frozen after receive the payload from the server(in the image the last two line are topic and payload, I put a black square to hide the topic and ip). I tested the sim sim800c and sim800L with arduino mqqt library and it works okay.

And also sometime if the sim800 lost connection or signal while is in the data mode, the code cannot detect this condition and the status is kept always like server is connected (SIM800.mqttServer.connect == 1). I dont know how to fix it, I give up.

thanks for read
![command](https://user-images.githubusercontent.com/44202176/119082920-0a77f500-b9cd-11eb-9ec2-3374ae1c32da.jpg)

**Comment by leech001** [comment]
Hi. A couple of questions:
1. Have you tried using the example from the library on your hardware?
2. Could you send me your code so that I could see how you use the library?

**Comment by killercuts** [comment]
Hello friend,
I am using the same example your shared, but I added some debug to usart2. I am using usart1 with sim800 and NUCLEO-F446RE.
I followed the instructions to create the project using STM32 toolchain (a pair of '.c / .h' and global interrupts) 
If I use the same code of the example (without HAL_UART_Transmit) I have the same problem. And I am using this broker broker.hivemq.com from [here](http://www.hivemq.com/demos/websocket-client/)

`if(SIM800.mqttReceive.newEvent) {`
   `unsigned char *topic = SIM800.mqttReceive.topic;`
   `HAL_UART_Transmit(&huart2, (uint8_t *)topic, strlen(topic), 70);`
   `HAL_UART_Transmit(&huart2, (uint8_t *)"\r\n", 2, 70);`
   `//int payload = atoi(SIM800.mqttReceive.payload);`
   `unsigned char *payload = SIM800.mqttReceive.payload;`
   `HAL_UART_Transmit(&huart2, (uint8_t *)payload, strlen(payload), 70);`
   `HAL_UART_Transmit(&huart2, (uint8_t *)"\r\n", 2, 70);`
   `SIM800.mqttReceive.newEvent = 0;`
  `}`

And I only change the size of the str in MQTT_Init from 32 to 50, because the APN here is long (32 characters).

`int MQTT_Init(void) {`
`...`
`char str[50] = {0};`
`...`
 `}`

for last, If I restart the module manually while the code is in the situation of data mode(sending), there is not way to detect if the modem fails, I mean change to this SIM800.mqttServer.connect == 0. sometimes due to current problem from battery the modem restarts while it is sending data.

<sorry my question and english. It was the first time I wrote sometime in github,>

**Comment by maheshlachake** [comment]
same problem

**Comment by maheshlachake** [comment]
I Have same problem. 
If anyone have any solution please share.

**Comment by leech001** [comment]
Hi. Try the [new version of the library](https://github.com/leech001/SIM800MQTT/tree/MQTTCheck) with the function of checking and reconnecting to the MQTT server if errors occur.
The way it works is to subscribe to your own posts one topic at a time. That is actually looping through the server and comparing what was sent and what came back. Maybe it will help to solve your problem.
