### ISSUE TITLE
AT+CIPSEND command

### ISSUE THREAD

**Issue by marco95thb** [leech001/SIM800MQTT#7]
Hi,

I'm studying your git repo for sending MQTT commands using STM32 with SIM800 series connected to STM32 through UART, using AT commands.

I'm a little confused by the function: MQTT_SUB: this function sentd over the UART the string coming from the function MQTTSerialize_publish but this string is not comatible with the at commands.
What's I'm missing? 
As far as I know the string should be published to  SIM800 using the command AT+CIPSEND"hello world"

How do you deal with it?
Thanks for the answer,
Marco.

**Comment by leech001** [comment]
Hi!
You missed the use of such a command as
AT+CIPMODE=1
```
error += SIM800_SendCommand("AT+CIPMODE=1\r\n", "OK\r\n", CMD_DELAY);
```
It sets the connection to transparent mode and it does not require you to send the command every time
AT+CIPSEND
when sending data when the connection is established.

[https://docviewer.yandex.ru/view/9195352/?page=11&*=7EfsmGUD89Xvbr3jW2A12TqDuMJ7InVybCI6Imh0dHBzOi8vY2RuLXNob3AuYWRhZnJ1aXQuY29tL2RhdGFzaGVldHMvc2ltODAwX3Nlcmllc190Y3BpcF9hcHBsaWNhdGlvbl9ub3RlX3YxLjAwLnBkZiIsInRpdGxlIjoic2ltODAwX3Nlcmllc190Y3BpcF9hcHBsaWNhdGlvbl9ub3RlX3YxLjAwLnBkZiIsIm5vaWZyYW1lIjp0cnVlLCJ1aWQiOiI5MTk1MzUyIiwidHMiOjE1Nzg2MzY3ODI1OTYsInl1IjoiNTAyMDkxNjA3MTU3NjY2NzQ0MiIsInNlcnBQYXJhbXMiOiJsYW5nPWVuJnRtPTE1Nzg2MzY2ODImdGxkPXJ1Jm5hbWU9c2ltODAwX3Nlcmllc190Y3BpcF9hcHBsaWNhdGlvbl9ub3RlX3YxLjAwLnBkZiZ0ZXh0PXNpbTgwMCt3ZWJzb2NrZXQmdXJsPWh0dHBzJTNBLy9jZG4tc2hvcC5hZGFmcnVpdC5jb20vZGF0YXNoZWV0cy9zaW04MDBfc2VyaWVzX3RjcGlwX2FwcGxpY2F0aW9uX25vdGVfdjEuMDAucGRmJmxyPTIxMyZtaW1lPXBkZiZsMTBuPXJ1JnNpZ249MDZiMTk3YWU4MTlhMDUwZTMwNTM5MzU1Y2NjZmJiYjYma2V5bm89MCJ9&lang=en](https://docviewer.yandex.ru/view/9195352/?page=11&*=7EfsmGUD89Xvbr3jW2A12TqDuMJ7InVybCI6Imh0dHBzOi8vY2RuLXNob3AuYWRhZnJ1aXQuY29tL2RhdGFzaGVldHMvc2ltODAwX3Nlcmllc190Y3BpcF9hcHBsaWNhdGlvbl9ub3RlX3YxLjAwLnBkZiIsInRpdGxlIjoic2ltODAwX3Nlcmllc190Y3BpcF9hcHBsaWNhdGlvbl9ub3RlX3YxLjAwLnBkZiIsIm5vaWZyYW1lIjp0cnVlLCJ1aWQiOiI5MTk1MzUyIiwidHMiOjE1Nzg2MzY3ODI1OTYsInl1IjoiNTAyMDkxNjA3MTU3NjY2NzQ0MiIsInNlcnBQYXJhbXMiOiJsYW5nPWVuJnRtPTE1Nzg2MzY2ODImdGxkPXJ1Jm5hbWU9c2ltODAwX3Nlcmllc190Y3BpcF9hcHBsaWNhdGlvbl9ub3RlX3YxLjAwLnBkZiZ0ZXh0PXNpbTgwMCt3ZWJzb2NrZXQmdXJsPWh0dHBzJTNBLy9jZG4tc2hvcC5hZGFmcnVpdC5jb20vZGF0YXNoZWV0cy9zaW04MDBfc2VyaWVzX3RjcGlwX2FwcGxpY2F0aW9uX25vdGVfdjEuMDAucGRmJmxyPTIxMyZtaW1lPXBkZiZsMTBuPXJ1JnNpZ249MDZiMTk3YWU4MTlhMDUwZTMwNTM5MzU1Y2NjZmJiYjYma2V5bm89MCJ9&lang=en)

**Comment by marco95thb** [comment]
Ok thanks for the answer. I'll go further with tests. Can you share where says that in trasparent mode does not require the command? I'm not able to find this info in the app note.
