### ISSUE TITLE
Execution blocked on SIM800_SendCommand 

### ISSUE THREAD

**Issue by mde398** [leech001/SIM800MQTT#8]
During the MQTT initialization (function MQTT_Init), the execution suddenly blocks on SIM800_SendCommand.

Below is a screenshot showing where the code stop working.

<img width="540" alt="error" src="https://user-images.githubusercontent.com/88838177/129212743-f4a6dded-7bd6-442b-8696-e89d2265d493.png">

I'm not able to understand why the code execution stops right there.

Do you have any suggstion on what to debug?

Thanks,

**Comment by leech001** [comment]
Hi. Check the settings for module response delays in the file MQTTSim800.h
If you don't use FREERTOS, you should have the parameter FREERTOS set to 0.
```
// === CONFIG ===
#define UART_SIM800 &huart2
#define FREERTOS    0
#define CMD_DELAY   2000
// ==============
```
If you use FREERTOS, you should have the parameter FREERTOS set to 1.
